### ISSUE TITLE
Not able to remove entities from specific sections

### ISSUE THREAD

**Issue by Thommav** [Prosono/SMARTi_BaseComponent#28]
Hello again. I’m a new user from Italy. Trying to setup this dashboard at the best for my system. I’m a pro user because I need it on many mobile devices. 

I’m experiencing that I’m not able to remove some entities from some specific sections. For example in the battery view or in the media devices. 
Even if I flag the entities as “not visible”, they stay there. 

Is there a procedure to be able to remove entities from those visualizations? 

Thanks

**Comment by Prosono** [comment]
Never mind, I got some free time and went over the code. If you reload the integration and restart HA things should be in order. Let me know if you find any locations the hidden entities still show up.

**Comment by Thommav** [comment]
Yes! I confirm. Generally It works. 
There is just an exception: the last line in the screenshot. 
You cannot make it "not visible" because is "made by SMARTi" i think and it doesn't have a unique ID.

![Image](https://github.com/user-attachments/assets/705ed697-f18a-46a1-a273-57cb0277f122)

![Image](https://github.com/user-attachments/assets/16176925-7af0-4663-bc62-284363d8868a)

**Comment by Prosono** [comment]
Okay, I've fixed the first issue with the "SMARTi" battery being there, the second I am working on trying to fix. Regarding your locks. Which number is the correct one, the 4 count or the two locks showing up in the popup? I suspect the last one?

**Comment by Thommav** [comment]
Yes, sorry. I was not clear. 
The right number of locks in my case is 2.

**Comment by Prosono** [comment]
I have not been able to fix the media players yet, but the battery section and I think the locks might be okay now. Could you please try to reload the integration and restart HA to check? The Multimedia stuff I will have to look at tomorrow if that's alright.

**Comment by Thommav** [comment]
Thank you for your prompt reaction. Really appreciated. 
Here my updates: 
- the last line of the battery section and it is still not possible to set that to "not visible";
- also for the locks, nothing changed;
- ok for the media players obviously
generally speaking, no rush buddy. You did a great job with this dashboard. 

Let me trow another issue on the table. In the energy management part everything seems to work like in the energy panel that is by default in HA but not this specific sensor. 
You can not even rename it for the same issue about the fact that it is an entity without a unique ID. 

![Image](https://github.com/user-attachments/assets/1119b5f2-0eba-4313-9c86-ff1e550b821f)
 
Thanks again

**Comment by Prosono** [comment]
Okay, I will have a look at this tomorrow then and give you some updares, its getting late and its time for bed :)

Regarding the power sensor, you need to set this sensor in the dashboard settings under the "power measurement device list" under "Dashboard Settings". Here you must select your sensor that has the total consumption for your home (same as the one you use in your energy panel. This will then make it visible in the top navigation bar as this is not possible to do with the selected sensor you put in your energy panel because HA is a bit weird that way.

**Comment by Thommav** [comment]
Good. Now the thing about the power sensor is clear and it works. 
It could be good to be able to rename it or to have it that takes the name of the specific sensor assigned. 

![Image](https://github.com/user-attachments/assets/43a4479e-700f-4559-8799-3727f28da988)

Here's is a very funny thing. In the top bar you can see that the system says that there is 1 light on and 1 movement sensor that detect a movement....in my case those ones are not real devices in my home....all the real ones are not hoghligheted in the bar as active even if they are....those 2 are the screen light level of the laptop I'm using and its mouse pad!!! This is a big bug :-)

![Image](https://github.com/user-attachments/assets/e90df3f9-470f-4071-9460-fc909c22ad45)

**Comment by Prosono** [comment]
Since the smarti_dynamic_power_sensor will be used for future automation to more easily control your energy management, it cannot be changed since it would break that feature when it will be released later. So for now, renaming it is not possible.

Regarding the last thing you mentioned. This is not a bug. You have included your laptop in HA which has a "motion sensor" e.g your mouse, and your screen which is defined as a light. There is no way for me to know that your screen on your laptop should not be shown winch to HA it is integrated as a light. The same goes for the motion. It's integrated into HA as a motion sensor. I suspect you might have done this with browser mod? 

I can look into not having them pop up at the status bar, but then you will have to hide the entities and I will have to do some more testing. 

If you really want to not have them show up, I suggest you delete them from your HA installation unless you desperately need them for something special.

**Comment by Thommav** [comment]
Got it. Ok, don’t worry for this one. I’ll remove those entities. I don’t need them at all. 
Thanks for the clarifications. Let’s focus on all the other small things to have this perfect also for other users.

**Comment by Prosono** [comment]
So I just wanted to give you a quick update on this issue. I've spent the last couple of days debugging this and I've finally found a way around the issue. I had to re-write a lot of code in order to get this working but I will need a couple of days to get everything implemented correctly so please be patient.

**Comment by Thommav** [comment]
Don’t worry. No rush. Thanks for the update and for all the job. Appreciated.

**Comment by Prosono** [comment]
If you use the pro version, you will now be able to hide entities correctly. I have not updated the basic version yet.

**Comment by Thommav** [comment]
Thanks a lot. 
Everything works with exception of the Locks number indicator in the Head bar. I have 2 locks and it continues to indicate 4.

**Comment by Prosono** [comment]
Yeah, I will look into it in the coming days. At least the filtering now works as intended which is nice :D. If you could open a second issue for it it will be easier for me to track it and prioritize it.
